### ISSUE TITLE
Include Technical Questions

### ISSUE THREAD

**Issue by tibssy** [tibssy/RoundZer0#6]
As a **candidate** I want to **the chatbot to include technical questions,** so that **demonstrate my skills directly during the interview.**

###  Acceptance criteria

- At least 3 technical questions must be included in each interview session.
- Questions must be job-relevant and appropriately challenging for the role.
- The chatbot must accept and evaluate technical answers.

### Tasks:

- [x] Create a new model for Assistant Preparation, where employers can define technical questions, interview duration.
- [x] Implement logic to select and ask technical questions during the interview session.
- [x] Add functionality for evaluating technical answers and providing feedback.
